name: Generate and Upload Image

on:
  schedule:
    - cron: '*/5 * * * *'  # 每五分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-and-upload-image:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码

    - name: Set timezone to Asia/Shanghai
      run: sudo timedatectl set-timezone Asia/Shanghai  # 设置时区为北京时间

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # 安装 Python 3.9

    - name: Install dependencies
      run: |
        pip install requests pillow beautifulsoup4  # 安装依赖库
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk  # 安装 Noto CJK 字体包，支持中文

    - name: Run Python script to generate image
      run: |
        python scripts/generate_image.py  # 执行 Python 脚本生成图片

    - name: Remove file history before 1 day ago
      run: |
        # 安装 git-filter-repo 工具
        sudo apt-get install -y python3-pip
        pip3 install git-filter-repo  # 安装 git-filter-repo

        # 删除 pic/richang.png 文件在 1 天前的提交记录
        git filter-repo --path pic/richang.png --before "1 day ago" --invert-paths

    - name: Commit and push updated repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .  # 将所有更改添加到 Git
        git commit -m "删除 pic/richang.png 文件 1 天前的历史记录"
        git push --force origin main  # 强制推送更新后的历史
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 来进行认证
